### ISSUE TITLE
Makefile issue

### ISSUE THREAD

**Issue by michelkiing** [persan/protobuf-ada#2]
Hello,
I'm getting this error when I try to compile the project :

bash-4.1$ make
make -C compiler build
make[1]: entrant dans le répertoire « /user4/ovs_ref/t0209433/Téléchargements/protobuf-ada-master/compiler »
/dlip_ref/s_dlip/Tools/gnat/v18.0/bin/gprbuild -p -P protoc_ada.gpr
Link
   [link]         protoc-ada.cc
/dlip_ref/s_dlip/Tools/protoc_linux/protobuf-3.5.1/lib/libprotobuf.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
gprbuild: link of protoc-ada.cc failed

It seems like i got the wrong version of protobuf or something like that ?

Thanks for your reply.

**Comment by persan** [comment]
Hi Michel.It was built using 2.6 libs when i got it, and I am painfully aware. I am working on a 3.7 build and ther is still  a set of inconsistencies. And I will be offline for at least 2 weeks grom now./PSkickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: Michel Cai <notifications@github.com> Datum: 2019-05-15  17:04  (GMT+01:00) Till: persan/protobuf-ada <protobuf-ada@noreply.github.com> Kopia: Subscribed <subscribed@noreply.github.com> Rubrik: [persan/protobuf-ada] Makefile issue (#2) Hello,

I'm getting this error when I try to compile the project :

bash-4.1$ make

make -C compiler build

make[1]: entrant dans le répertoire « /user4/ovs_ref/t0209433/Téléchargements/protobuf-ada-master/compiler »

/dlip_ref/s_dlip/Tools/gnat/v18.0/bin/gprbuild -p -P protoc_ada.gpr

Link

[link]         protoc-ada.cc

/dlip_ref/s_dlip/Tools/protoc_linux/protobuf-3.5.1/lib/libprotobuf.so: file not recognized: File format not recognized

collect2: error: ld returned 1 exit status

gprbuild: link of protoc-ada.cc failed

It seems like i got the wrong version of protobuf or something like that ?

Thanks for your reply.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/persan/protobuf-ada/issues/2?email_source=notifications\u0026email_token=AABZATHTB4Q7BMIRGUDZKPDPVQRBXA5CNFSM4HNEH4TKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GT6NEEA",

"url": "https://github.com/persan/protobuf-ada/issues/2?email_source=notifications\u0026email_token=AABZATHTB4Q7BMIRGUDZKPDPVQRBXA5CNFSM4HNEH4TKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GT6NEEA",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by michelkiing** [comment]
hi, thx for the reply, I just installed the 2-6 lib, now i'm getting a new error :
/protobuf-2.6.0/lib/libprotobuf.a: error adding symbols: File format not recognized

**Comment by persan** [comment]
That is probanly casued by different versions of the compilers.My sugestion would be to download the sources and then compile with your current gcc/gnat  and install them in the gcc/gnat installation.configure --prefix=gnat installation ....makemake install /PSkickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: Michel Cai <notifications@github.com> Datum: 2019-05-16  11:26  (GMT+01:00) Till: persan/protobuf-ada <protobuf-ada@noreply.github.com> Kopia: Per Sandberg <per.s.sandberg@bahnhof.se>, Comment <comment@noreply.github.com> Rubrik: Re: [persan/protobuf-ada] Makefile issue (#2) hi, thx for the reply, I just installed the 2-6 lib, now i'm getting a new error :
/protobuf-2.6.0/lib/libprotobuf.a: error adding symbols: File format not recognized

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/persan/protobuf-ada/issues/2?email_source=notifications\u0026email_token=AABZATDGHASVN5F4L32EPL3PVUSDLA5CNFSM4HNEH4TKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVRHIGQ#issuecomment-492991514",
"url": "https://github.com/persan/protobuf-ada/issues/2?email_source=notifications\u0026email_token=AABZATDGHASVN5F4L32EPL3PVUSDLA5CNFSM4HNEH4TKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVRHIGQ#issuecomment-492991514",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by michelkiing** [comment]
Hi, I succesfully compiled the project, but when I tried to build up the example, I got this error :
gprbuild -j0 -p -P example_ada.gpr
Build Libraries
   [gprlib]       google-protobuf.lexch
gprlib: no object files specified
gprbuild: could not build library for project google.protobuf
make: *** [add_person_ada] Erreur 4

I checked, and the file is created but not found

**Comment by foo-fee** [comment]
Hi Persan

I'm now compiling and linking on macOS Catalina with protobuf: stable 3.11.4 and gcc (GCC) 8.3.1 20190518 (for GNAT Community 2019 20190517). I still need to fix with libstdcpp.gpr since it contains stuff not valid on my platform.
